component: http
name: http-express-8sJQ81O5tx
inputs:
  src:
    src: ./
    exclude:
      - .env
      - client
  faas:
    framework: express
    name: "${name}"
    runtime: Nodejs16.13
    eip: false
    timeout: 3
    memorySize: 1024
    tags: []
    environments: []
    layers:
      - name: "${output:${stage}:${app}:douyin-demo-layer.name}"
        version: "${output:${stage}:${app}:douyin-demo-layer.version}"
  apigw:
    protocols:
      - http
      - https
    timeout: 60
    environment: release
    customDomains:
      - domain: tools.v-hiker.cn
        certId: wH24Kimq
        protocols:
          - https
        pathMap:
          - path: /
            environment: release
        customMap: true
        isDefaultMapping: false
  region: ap-guangzhou
  isAutoCiDeploy: false
org: "1252911770"
app: douyin-demo
stage: dev
